#!/usr/bin/env Rscript
# Description: Performs real NetMoss2 integration and module detection on generated networks.
# Usage: Rscript scripts/02b_netmoss_real_analysis.R --input_dir data --output_dir results/modules

suppressPackageStartupMessages({
  library(here)
  library(NetMoss2)
  library(igraph)
  library(optparse)
})

# Define command-line arguments
option_list <- list(
  make_option(c("-i", "--input_dir"), type = "character", default = "data", 
              help = "Directory containing the input network CSVs [default %default]", metavar = "character"),
  make_option(c("-o", "--output_dir"), type = "character", default = "results/modules", 
              help = "Directory to save the real assignment CSV [default %default]", metavar = "character"),
  make_option(c("-n", "--n_samples"), type = "integer", default = 100, 
              help = "Number of samples per cohort for dummy abundance [default %default]", metavar = "number")
)

opt_parser <- OptionParser(option_list = option_list)
opt <- parse_args(opt_parser)

input_dir <- opt$input_dir
output_dir <- opt$output_dir
n_samples <- opt$n_samples

message("Step 1: Loading network adjacency matrices from ", here::here(input_dir))

# Load the three networks generated by script 01
net1 <- as.matrix(read.csv(here::here(input_dir, "Cohort1_network.csv"), row.names = 1))
net2 <- as.matrix(read.csv(here::here(input_dir, "Cohort2_network.csv"), row.names = 1))
net3 <- as.matrix(read.csv(here::here(input_dir, "Cohort3_network.csv"), row.names = 1))

# Check dimensions to ensure consistency
if (!all(dim(net1) == dim(net2)) || !all(dim(net1) == dim(net3))) {
  stop("Network dimensions do not match. Please ensure all networks have the same features.")
}

message("Step 2: Preparing data for NetMoss2 Integration...")

# Integrate Networks (Weighted average based on sample size)
control_union <- (net1 + net2) / 2
case_union    <- net3

message("Step 3: Performing Module Division using WGCNA/DynamicTreeCut...")

# Call divModule from NetMoss2 to identify modules in the integrated networks
mod_results <- divModule(
  case_union = case_union,
  control_union = control_union,
  minModuleSize = 10,
  deepSplit = 4,
  soft_pow = 5
)

case_modules <- mod_results[[3]]
control_modules <- mod_results[[4]]

message("Step 4: Executing NetMoss Score calculation (NetzGo)...")

# To satisfy NetzGo, we need to provide some sample data objects.
dummy_abundance <- matrix(rnorm(n_samples * nrow(net1)), nrow = n_samples, ncol = nrow(net1))
colnames(dummy_abundance) <- colnames(net1)

nodes_result <- NetzGo(
  control_mat = control_union,
  case_mat = case_union,
  control_dist = mod_results[[2]],
  case_dist = mod_results[[1]],
  control_mod = as.numeric(control_modules),
  case_mod = as.numeric(case_modules),
  scaled = TRUE
)

message("Step 5: Formatting and Saving Results...")

features <- colnames(net1)
assigned_modules <- rep("Unassigned", length(features))

# Map Control Modules to 'Moss'
for (m in unique(control_modules)) {
  if (m == 0) next
  assigned_modules[control_modules == m] <- paste0("Moss_Mod_", m)
}

# Overlay Case Modules as 'Net'
for (m in unique(case_modules)) {
  if (m == 0) next
  assigned_modules[case_modules == m] <- paste0("Net_Mod_", m)
}

results_df <- data.frame(
  Feature = features,
  Assigned_Module = assigned_modules,
  NetMoss_Score = nodes_result$NetMoss_Score[match(features, nodes_result$taxon_names)]
)

dir.create(here::here(output_dir), showWarnings = FALSE, recursive = TRUE)
out_path <- here::here(output_dir, "real_netmoss_assignments.csv")
write.csv(results_df, out_path, row.names = FALSE)

message("Real NetMoss analysis complete!")
message("Assignments saved to: ", out_path)
