#!/usr/bin/env Rscript
# Description: Performs real NetMoss2 integration and module detection on generated networks.
# Author: Expert R Bioinformatics Developer
# Date: 2026-05-14

suppressPackageStartupMessages({
  library(here)
  library(NetMoss2)
  library(igraph)
})

message("Step 1: Loading network adjacency matrices...")

# Load the three networks generated by script 01
net1 <- as.matrix(read.csv(here::here("data", "Cohort1_network.csv"), row.names = 1))
net2 <- as.matrix(read.csv(here::here("data", "Cohort2_network.csv"), row.names = 1))
net3 <- as.matrix(read.csv(here::here("data", "Cohort3_network.csv"), row.names = 1))

# Check dimensions to ensure consistency
if (!all(dim(net1) == dim(net2)) || !all(dim(net1) == dim(net3))) {
  stop("Network dimensions do not match. Please ensure all networks have the same features.")
}

message("Step 2: Preparing data for NetMoss2 Integration...")

# NetMoss2's NetMoss() function typically expects directory paths or file paths
# for both abundance and network data. Since we have pre-calculated networks
# and no abundance data, we will perform the integration and module division
# using the internal logic of NetMoss2 for maximum control and transparency.

# 1. Integrate Networks (Weighted average based on sample size)
# For this demo, we assume equal weights (n=100 for each cohort)
control_union <- (net1 + net2) / 2
case_union    <- net3

message("Step 3: Performing Module Division using WGCNA/DynamicTreeCut...")

# Call divModule from NetMoss2 to identify modules in the integrated networks
# This uses the same parameters as the default NetMoss() wrapper
mod_results <- divModule(
  case_union = case_union,
  control_union = control_union,
  minModuleSize = 10, # Adjusted for the mock data size
  deepSplit = 4,
  soft_pow = 5
)

# Extract module assignments
# dynamicMods_case is element [[3]], dynamicMods_control is element [[4]]
case_modules <- mod_results[[3]]
control_modules <- mod_results[[4]]

message("Step 4: Executing NetMoss Score calculation (NetzGo)...")

# To satisfy NetzGo, we need to provide some sample data objects.
# We create dummy matrices matching the feature count.
dummy_abundance <- matrix(rnorm(100 * nrow(net1)), nrow = 100, ncol = nrow(net1))
colnames(dummy_abundance) <- colnames(net1)

nodes_result <- NetzGo(
  control_mat = control_union,
  case_mat = case_union,
  control_dist = mod_results[[2]], # dissTOM_control
  case_dist = mod_results[[1]],    # dissTOM_case
  control_mod = as.numeric(control_modules),
  case_mod = as.numeric(case_modules),
  scaled = TRUE
)

message("Step 5: Formatting and Saving Results...")

# Create the final data frame with feature assignments.
# We map the numeric module IDs to descriptive names.
# Convention: Modules found in the integrated control network are 'Moss' (conserved)
# and those shifting in the case network are 'Net' (context-specific).

features <- colnames(net1)
assigned_modules <- rep("Unassigned", length(features))

# Map Control Modules to 'Moss'
for (m in unique(control_modules)) {
  if (m == 0) next # 0 usually represents unassigned in DynamicTreeCut
  assigned_modules[control_modules == m] <- paste0("Moss_Mod_", m)
}

# Overlay Case Modules as 'Net' if they represent a shift
# (Simplification: any module assignment in the case network is labeled 'Net')
for (m in unique(case_modules)) {
  if (m == 0) next
  assigned_modules[case_modules == m] <- paste0("Net_Mod_", m)
}

results_df <- data.frame(
  Feature = features,
  Assigned_Module = assigned_modules,
  NetMoss_Score = nodes_result$NetMoss_Score[match(features, nodes_result$taxon_names)]
)

# Create output directory
dir.create(here::here("results", "modules"), showWarnings = FALSE, recursive = TRUE)

out_path <- here::here("results", "modules", "real_netmoss_assignments.csv")
write.csv(results_df, out_path, row.names = FALSE)

message("Real NetMoss analysis complete!")
message("Assignments saved to: ", out_path)
message("NetMoss Scores incorporated into assignments file.")
